# Changing to down makes it less "wide"
direction: down

# Grid layout forces components into a square-like matrix
Docker Composed Application: {
  style: {
    stroke-dash: 5
  }


  Frontend: React / Node.js
  Backend: FastAPI
  DiscordBot: Discord Bot
  DB: SQLite {
    shape: cylinder
  }

  Frontend -> Backend: CRUD
  Backend -> DiscordBot: Webhook Notifications
  Backend -> DB
}

# Grouping users to sit closer together
Users: {
  style: { stroke-width: 0; fill: transparent }
  User: User {
    shape: person
  }
}

SMTP: SMTP (optional) {
  shape: cloud
}

Discord API: Discord API {
  shape: cloud
}

Users.User -> Docker Composed Application.Frontend: Interacts

Docker Composed Application.DiscordBot <-> Discord API: Events & Messages
Discord API <-> Users.User

Docker Composed Application.Backend -> SMTP: Email?
SMTP -> Users.User
