from .auth import router as auth_router
from .health import router as health_router
from .users import router as users_router
from .callings import router as callings_router
from .assignments import router as assignments_router
from .speaking import router as speaking_router
from .calling_kanban import router as calling_kanban_router
from .ward import router as ward_router
from .presidency import router as presidency_router
from .temple_config import router as temple_config_router
from .appointment_types import router as appointment_types_router
from .appointment_availability import router as appointment_availability_router
from .appointment_bookings import router as appointment_bookings_router
from .building_reservation import router as building_reservation_router