from .auth import router as auth_router
from .health import router as health_router
from .users import router as users_router
from .callings import router as callings_router
from .assignments import router as assignments_router
from .speaking import router as speaking_router
from .calling_kanban import router as calling_kanban_router
from .ward import router as ward_router
from .presidency import router as presidency_router