"""Ward

Revision ID: 279b3b9fc73c
Revises: 36977e076577
Create Date: 2026-04-07 15:25:22.279120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '279b3b9fc73c'
down_revision: Union[str, Sequence[str], None] = '36977e076577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bishop_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bishop_id'], ['usercalling.id'], name=op.f('fk_ward_bishop_id_usercalling')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ward'))
    )
    with op.batch_alter_table('usercalling', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_usercalling_calling_id_calling'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_usercalling_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_calling_id_calling'), 'calling', ['calling_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercalling', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usercalling_user_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_usercalling_calling_id_calling'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_calling_id_calling'), 'calling', ['calling_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('ward')
    # ### end Alembic commands ###
