"""Calling Kanban

Revision ID: 36977e076577
Revises: 4f56f0685188
Create Date: 2026-03-23 16:22:05.754976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36977e076577'
down_revision: Union[str, Sequence[str], None] = '4f56f0685188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakingtopic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_material', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakingtopic'))
    )
    with op.batch_alter_table('speakingtopic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakingtopic_month'), ['month'], unique=False)

    op.create_table('callingproposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spouse_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_calling', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.Integer(), nullable=False),
    sa.Column('is_release', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitter'], ['user.id'], name=op.f('fk_callingproposal_submitter_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callingproposal'))
    )
    with op.batch_alter_table('callingproposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callingproposal_submitter'), ['submitter'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('high_councilor_id', sa.Integer(), nullable=True),
    sa.Column('responsibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('committee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['high_councilor_id'], ['usercalling.id'], name=op.f('fk_assignment_high_councilor_id_usercalling')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_high_councilor_id'), ['high_councilor_id'], unique=False)

    op.create_table('callingapproval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], name=op.f('fk_callingapproval_approver_id_user')),
    sa.ForeignKeyConstraint(['proposal_id'], ['callingproposal.id'], name=op.f('fk_callingapproval_proposal_id_callingproposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callingapproval'))
    )
    with op.batch_alter_table('callingapproval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callingapproval_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callingapproval_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('callingcomment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('commenter_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['user.id'], name=op.f('fk_callingcomment_commenter_id_user')),
    sa.ForeignKeyConstraint(['proposal_id'], ['callingproposal.id'], name=op.f('fk_callingcomment_proposal_id_callingproposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callingcomment'))
    )
    with op.batch_alter_table('callingcomment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callingcomment_commenter_id'), ['commenter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callingcomment_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('callinginterview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interviewer_id'], ['user.id'], name=op.f('fk_callinginterview_interviewer_id_user')),
    sa.ForeignKeyConstraint(['proposal_id'], ['callingproposal.id'], name=op.f('fk_callinginterview_proposal_id_callingproposal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callinginterview'))
    )
    with op.batch_alter_table('callinginterview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callinginterview_interviewer_id'), ['interviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callinginterview_proposal_id'), ['proposal_id'], unique=False)

    op.create_table('kanbanupdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('updater_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('SP_APPROVAL', 'HC_APPROVAL', 'INTERVIEW', 'SUSTAIN', 'SET_APART', 'LCR_UPDATE', 'DONE', name='kanbanstages'), nullable=True),
    sa.Column('to_stage', sa.Enum('SP_APPROVAL', 'HC_APPROVAL', 'INTERVIEW', 'SUSTAIN', 'SET_APART', 'LCR_UPDATE', 'DONE', name='kanbanstages'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['callingproposal.id'], name=op.f('fk_kanbanupdate_proposal_id_callingproposal')),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], name=op.f('fk_kanbanupdate_updater_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kanbanupdate'))
    )
    with op.batch_alter_table('kanbanupdate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kanbanupdate_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kanbanupdate_updater_id'), ['updater_id'], unique=False)

    op.create_table('speakingassignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('high_councilor_id', sa.Integer(), nullable=True),
    sa.Column('speaker2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['high_councilor_id'], ['usercalling.id'], name=op.f('fk_speakingassignment_high_councilor_id_usercalling')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speakingassignment'))
    )
    with op.batch_alter_table('speakingassignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakingassignment_high_councilor_id'), ['high_councilor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakingassignment_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakingassignment_ward_id'), ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercalling', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usercalling_calling_id_calling'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_usercalling_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_calling_id_calling'), 'calling', ['calling_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_usercalling_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('speakingassignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakingassignment_ward_id'))
        batch_op.drop_index(batch_op.f('ix_speakingassignment_month'))
        batch_op.drop_index(batch_op.f('ix_speakingassignment_high_councilor_id'))

    op.drop_table('speakingassignment')
    with op.batch_alter_table('kanbanupdate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kanbanupdate_updater_id'))
        batch_op.drop_index(batch_op.f('ix_kanbanupdate_proposal_id'))

    op.drop_table('kanbanupdate')
    with op.batch_alter_table('callinginterview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callinginterview_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_callinginterview_interviewer_id'))

    op.drop_table('callinginterview')
    with op.batch_alter_table('callingcomment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callingcomment_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_callingcomment_commenter_id'))

    op.drop_table('callingcomment')
    with op.batch_alter_table('callingapproval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callingapproval_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_callingapproval_approver_id'))

    op.drop_table('callingapproval')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_high_councilor_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('callingproposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callingproposal_submitter'))

    op.drop_table('callingproposal')
    with op.batch_alter_table('speakingtopic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakingtopic_month'))

    op.drop_table('speakingtopic')
    # ### end Alembic commands ###
