"""add temple recommend appointment tables

Revision ID: 52a3bd027c48
Revises: 594f602a3097
Create Date: 2026-06-23 14:08:41.038085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '52a3bd027c48'
down_revision: Union[str, Sequence[str], None] = '594f602a3097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointmenttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('system_defined', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointmenttype')),
    sa.UniqueConstraint('name', name=op.f('uq_appointmenttype_name'))
    )
    op.create_table('templerecommendconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('open_hours_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exception_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slot_buffer_mins', sa.Integer(), nullable=False),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('booking_cutoff_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templerecommendconfig'))
    )
    op.create_table('availabilityexception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_availabilityexception_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilityexception'))
    )
    op.create_table('availabilitywindow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_availabilitywindow_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilitywindow'))
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('member_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_minute_of_day', sa.Integer(), nullable=False),
    sa.Column('end_minute_of_day', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_EMAIL_CONFIRM', 'CONFIRMED', 'EXPIRED', 'CANCELLED_BY_MEMBER', 'CANCELLED_BY_PRESIDENCY', 'COMPLETED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('confirmation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('calendar_sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointmenttype.id'], name=op.f('fk_booking_appointment_type_id_appointmenttype')),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['user.id'], name=op.f('fk_booking_cancelled_by_user_id_user')),
    sa.ForeignKeyConstraint(['interviewer_user_id'], ['user.id'], name=op.f('fk_booking_interviewer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking')),
    sa.UniqueConstraint('confirmation_token', name=op.f('uq_booking_confirmation_token')),
    sa.UniqueConstraint('start_datetime', 'interviewer_user_id', name='uq_booking_slot')
    )
    op.create_table('bookingauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_bookingauditlog_actor_user_id_user')),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_bookingauditlog_booking_id_booking')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookingauditlog'))
    )
    # ### end Alembic commands ###

    # Backfill MANAGE_APPOINTMENTS (512) onto rows that already have all non-DISCORD_BOT flags set.
    # 383 = 1|2|4|8|16|32|64|256 (all non-DISCORD_BOT, non-MANAGE_APPOINTMENTS flags).
    # Any row with (scopes & 383) == 383 already has "all" permissions and should gain 512 too.
    op.execute(
        "UPDATE permissions SET scopes = scopes | 512 WHERE (scopes & 383) = 383"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookingauditlog')
    op.drop_table('booking')
    op.drop_table('availabilitywindow')
    op.drop_table('availabilityexception')
    op.drop_table('templerecommendconfig')
    op.drop_table('appointmenttype')
    # ### end Alembic commands ###
