"""phase3_reschedule_reminder_fields

Revision ID: 6485b4767492
Revises: 65974fd3382a
Create Date: 2026-06-26 22:12:16.099608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6485b4767492'
down_revision: Union[str, Sequence[str], None] = '65974fd3382a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reschedule_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_reschedule_token'), ['reschedule_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_reschedule_token'))
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reschedule_token')

    # ### end Alembic commands ###
