"""add recurrence to availability exception

Revision ID: 65974fd3382a
Revises: 52a3bd027c48
Create Date: 2026-06-23 23:33:35.436452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65974fd3382a'
down_revision: Union[str, Sequence[str], None] = '52a3bd027c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilityexception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availabilityexception', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
