"""add site_settings table

Revision ID: 74ad0abe6025
Revises: e45a10b5084e
Create Date: 2026-06-27 22:29:29.384671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '74ad0abe6025'
down_revision: Union[str, Sequence[str], None] = 'e45a10b5084e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitesettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stake_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('stake_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('reply_to_email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('hero_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('hero_subtitle', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('hero_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sacrament_times', sqlite.JSON(), nullable=True),
    sa.Column('hidden_pages', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sitesettings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitesettings')
    # ### end Alembic commands ###
