"""add presidency_assignment table

Revision ID: cb1e4fd71072
Revises: 279b3b9fc73c
Create Date: 2026-06-07 00:40:29.655177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb1e4fd71072'
down_revision: Union[str, Sequence[str], None] = '279b3b9fc73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presidency_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calling_id', sa.Integer(), nullable=False),
    sa.Column('responsibilities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wards_overseen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['calling_id'], ['calling.id'], name=op.f('fk_presidency_assignment_calling_id_calling'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presidency_assignment'))
    )
    with op.batch_alter_table('presidency_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presidency_assignment_calling_id'), ['calling_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presidency_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presidency_assignment_calling_id'))

    op.drop_table('presidency_assignment')
    # ### end Alembic commands ###
