"""Add Calling and Permissions

Revision ID: e400ea3164f4
Revises: 4779cfc6cc09
Create Date: 2026-01-25 22:05:55.268088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e400ea3164f4'
down_revision: Union[str, Sequence[str], None] = '4779cfc6cc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_slots', sa.Integer(), nullable=False),
    sa.Column('system_defined', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calling', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calling_name'), ['name'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_calling', sa.Boolean(), nullable=False),
    sa.Column('scopes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foreign_id', 'is_calling', name='unique_subject_permission')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_foreign_id'), ['foreign_id'], unique=False)

    op.create_table('usercalling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calling_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calling_id'], ['calling.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usercalling', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usercalling_calling_id'), ['calling_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usercalling_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calling')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calling', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('usercalling', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usercalling_user_id'))
        batch_op.drop_index(batch_op.f('ix_usercalling_calling_id'))

    op.drop_table('usercalling')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_foreign_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('calling', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calling_name'))

    op.drop_table('calling')
    # ### end Alembic commands ###
