"""add building_reservation table

Revision ID: e45a10b5084e
Revises: 6485b4767492
Create Date: 2026-06-27 21:10:19.899574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e45a10b5084e'
down_revision: Union[str, Sequence[str], None] = '6485b4767492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildingreservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('setup_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cleanup_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rooms', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organizer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_other', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('needs_access', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='reservationstatus'), nullable=False),
    sa.Column('denial_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_buildingreservation_reviewed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildingreservation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildingreservation')
    # ### end Alembic commands ###
